# PocketDarwin CMake toolchain file
set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR arm64)

set(POCKETDARWIN_SDK "${CMAKE_CURRENT_LIST_DIR}/../PocketDarwin.sdk")
set(POCKETDARWIN_TOOLCHAIN "${CMAKE_CURRENT_LIST_DIR}/Toolchains/PocketDarwin.xctoolchain")

set(CMAKE_SYSROOT "${POCKETDARWIN_SDK}")

set(CMAKE_C_COMPILER "${POCKETDARWIN_TOOLCHAIN}/usr/bin/clang")
set(CMAKE_CXX_COMPILER "${POCKETDARWIN_TOOLCHAIN}/usr/bin/clang++")

set(CMAKE_FIND_ROOT_PATH "${POCKETDARWIN_SDK}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
