include $(GNUSTEP_MAKEFILES)/common.make

# The name of your executable
TOOL_NAME = CoreOS

# The list of Objective-C source files
CoreOS_OBJC_FILES = main.m \
					FDSystem.m \
					FDUser.m \
					FDUserSession.m \
					FDUtsname.m \
					FDTuxedo.m \
					SystemTypeIdner.m \
					libSystemGrepper.m

# Include the rules for command-line tools
include $(GNUSTEP_MAKEFILES)/tool.make
